# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-API-Remote
version:      0.07
version_from: Remote.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
